// Generated by `npm run seed:build`; do not edit by hand.

export const SAMPLE_PROJECTS = [
  {
    id: 'a794456d-6d1b-5b55-a360-13fec83dc7bc',
    name: 'acme-shop',
    language: 'php',
    framework: 'laravel',
    fileCount: 53,
    symbolCount: 121,
    edgeCount: 170,
    commitCount: 32,
  },
] as const;
