import { randomUUID } from 'node:crypto';
import { describe, expect, it } from 'vitest';
import type { SeedRows } from '@codemind/adapter-store-postgres';
import { projectKey, seedId } from '../../../packages/cli/src/seed/deterministic-ids';
import { renderSampleProjects } from '../../../packages/cli/src/seed/render-sample-projects';

// Spec: openspec/changes/seed-load-and-projects/specs/seed-build/spec.md → "Sample-project constant".
// The `it` named after a scenario is that scenario; the others are extra cases.

/** One project with two files, three symbols, one edge and two commits, under fresh random ids. */
function rows(framework: string | null = 'laravel'): SeedRows {
  const projectId = randomUUID();
  const a = randomUUID();
  const b = randomUUID();
  const s1 = randomUUID();
  const s2 = randomUUID();
  return {
    project: {
      id: projectId,
      name: '__codemind_seed_build__',
      root_path: '/tmp/x',
      language: 'php',
      framework,
      is_sample: false,
      indexed_commit: 'f'.repeat(40),
      node_count: 0,
      edge_count: 0,
      indexed_at: null,
      created_at: new Date('2030-01-01T00:00:00.000Z'),
    },
    files: [
      { id: a, project_id: projectId, path: 'a.php', kind: 'source', loc: 1, content_hash: 'h', redacted: false },
      { id: b, project_id: projectId, path: 'b.php', kind: 'source', loc: 1, content_hash: 'h', redacted: false },
    ],
    symbols: [
      { id: s1, file_id: a, path: 'a.php', name: 'A', kind: 'class', start_line: 1, end_line: 2, signature: null },
      { id: s2, file_id: b, path: 'b.php', name: 'B', kind: 'class', start_line: 1, end_line: 2, signature: null },
      { id: randomUUID(), file_id: b, path: 'b.php', name: 'run', kind: 'method', start_line: 3, end_line: 4, signature: null },
    ],
    edges: [
      { id: randomUUID(), project_id: projectId, source_symbol_id: s1, source_file_id: null, target_symbol_id: s2, target_file_id: null, kind: 'calls', resolution: 'exact', extractor: 'php', weight: null },
    ],
    commits: [
      { id: randomUUID(), project_id: projectId, sha: 'f'.repeat(40), message: 'a', author_hash: 'x', committed_at: new Date('2024-01-01T00:00:00.000Z'), pr_number: null },
      { id: randomUUID(), project_id: projectId, sha: '1'.repeat(40), message: 'b', author_hash: 'y', committed_at: new Date('2023-01-01T00:00:00.000Z'), pr_number: null },
    ],
    fileCommits: [],
  };
}

/** A deterministic Fisher–Yates shuffle driven by a small linear congruential generator. */
function shuffle<T>(items: T[], seed: number): T[] {
  const result = [...items];
  let state = seed;
  for (let i = result.length - 1; i > 0; i -= 1) {
    state = (state * 1103515245 + 12345) % 2147483648;
    // The high bits: the low bits of this generator cycle with a short period.
    const j = Math.floor((state / 2147483648) * (i + 1));
    [result[i], result[j]] = [result[j], result[i]];
  }
  return result;
}

/** The same graph with every table shuffled by `seed`. */
function shuffled(input: SeedRows, seed: number): SeedRows {
  return {
    ...input,
    files: shuffle(input.files, seed),
    symbols: shuffle(input.symbols, seed + 1),
    edges: shuffle(input.edges, seed + 2),
    commits: shuffle(input.commits, seed + 3),
    fileCommits: shuffle(input.fileCommits, seed + 4),
  };
}

describe('renderSampleProjects', () => {
  it('The constant does not depend on row order', () => {
    // Arrange: the same graph under other random ids, its tables shuffled with several seeds.
    const first = rows();
    const others = [1, 7, 42, 1000].map((seed) => shuffled(rows(), seed));

    // Act
    const a = renderSampleProjects(first, 'acme-shop');
    const texts = others.map((other) => renderSampleProjects(other, 'acme-shop'));

    // Assert
    expect(new Set(others.map((other) => other.symbols.map((s) => s.name).join(','))).size).toBeGreaterThan(1);
    for (const text of texts) expect(text).toBe(a);
  });

  it('writes exactly the template, with the derived id and the counts of the rows', () => {
    expect(renderSampleProjects(rows(), 'acme-shop')).toBe(
      [
        '// Generated by `npm run seed:build`; do not edit by hand.',
        '',
        'export const SAMPLE_PROJECTS = [',
        '  {',
        `    id: '${seedId(projectKey('acme-shop'))}',`,
        "    name: 'acme-shop',",
        "    language: 'php',",
        "    framework: 'laravel',",
        '    fileCount: 2,',
        '    symbolCount: 3,',
        '    edgeCount: 1,',
        '    commitCount: 2,',
        '  },',
        '] as const;',
        '',
      ].join('\n'),
    );
  });

  it('writes a missing framework as null, without quotes', () => {
    expect(renderSampleProjects(rows(null), 'acme-shop')).toContain('\n    framework: null,\n');
  });

  it('escapes quotes and backslashes in strings', () => {
    expect(renderSampleProjects(rows(), "o'shop\\x")).toContain("\n    name: 'o\\'shop\\\\x',\n");
  });
});
