import { randomUUID } from 'node:crypto';
import { describe, expect, it } from 'vitest';
import type { SeedRows } from '@codemind/adapter-store-postgres';
import { projectKey, seedId } from '../../../packages/cli/src/seed/deterministic-ids';
import { renderSampleProjects } from '../../../packages/cli/src/seed/render-sample-projects';

// Spec: openspec/changes/seed-load-and-projects/specs/seed-build/spec.md → "Sample-project constant".
// The `it` named after a scenario is that scenario; the others are extra cases.

/** One project with two files, three symbols, one edge and two commits, under fresh random ids. */
function rows(framework: string | null = 'laravel'): SeedRows {
  const projectId = randomUUID();
  const a = randomUUID();
  const b = randomUUID();
  const s1 = randomUUID();
  const s2 = randomUUID();
  return {
    project: {
      id: projectId,
      name: '__codemind_seed_build__',
      root_path: '/tmp/x',
      language: 'php',
      framework,
      is_sample: false,
      indexed_commit: 'f'.repeat(40),
      node_count: 0,
      edge_count: 0,
      indexed_at: null,
      created_at: new Date('2030-01-01T00:00:00.000Z'),
    },
    files: [
      { id: a, project_id: projectId, path: 'a.php', kind: 'source', loc: 1, content_hash: 'h', redacted: false },
      { id: b, project_id: projectId, path: 'b.php', kind: 'source', loc: 1, content_hash: 'h', redacted: false },
    ],
    symbols: [
      { id: s1, file_id: a, path: 'a.php', name: 'A', kind: 'class', start_line: 1, end_line: 2, signature: null },
      { id: s2, file_id: b, path: 'b.php', name: 'B', kind: 'class', start_line: 1, end_line: 2, signature: null },
      { id: randomUUID(), file_id: b, path: 'b.php', name: 'run', kind: 'method', start_line: 3, end_line: 4, signature: null },
    ],
    edges: [
      { id: randomUUID(), project_id: projectId, source_symbol_id: s1, source_file_id: null, target_symbol_id: s2, target_file_id: null, kind: 'calls', resolution: 'exact', extractor: 'php', weight: null },
    ],
    commits: [
      { id: randomUUID(), project_id: projectId, sha: 'f'.repeat(40), message: 'a', author_hash: 'x', committed_at: new Date('2024-01-01T00:00:00.000Z'), pr_number: null },
      { id: randomUUID(), project_id: projectId, sha: '1'.repeat(40), message: 'b', author_hash: 'y', committed_at: new Date('2023-01-01T00:00:00.000Z'), pr_number: null },
    ],
    fileCommits: [],
  };
}

function shuffled(input: SeedRows): SeedRows {
  return {
    ...input,
    files: [...input.files].reverse(),
    symbols: [...input.symbols].reverse(),
    edges: [...input.edges].reverse(),
    commits: [...input.commits].reverse(),
    fileCommits: [...input.fileCommits].reverse(),
  };
}

describe('renderSampleProjects', () => {
  it('The constant does not depend on row order', () => {
    // Arrange
    const first = rows();
    const second = shuffled(rows());

    // Act
    const a = renderSampleProjects(first, 'acme-shop');
    const b = renderSampleProjects(second, 'acme-shop');

    // Assert
    expect(b).toBe(a);
  });

  it('writes exactly the template, with the derived id and the counts of the rows', () => {
    expect(renderSampleProjects(rows(), 'acme-shop')).toBe(
      [
        '// Generated by `npm run seed:build`; do not edit by hand.',
        '',
        'export const SAMPLE_PROJECTS = [',
        '  {',
        `    id: '${seedId(projectKey('acme-shop'))}',`,
        "    name: 'acme-shop',",
        "    language: 'php',",
        "    framework: 'laravel',",
        '    fileCount: 2,',
        '    symbolCount: 3,',
        '    edgeCount: 1,',
        '    commitCount: 2,',
        '  },',
        '] as const;',
        '',
      ].join('\n'),
    );
  });

  it('writes a missing framework as null, without quotes', () => {
    expect(renderSampleProjects(rows(null), 'acme-shop')).toContain('\n    framework: null,\n');
  });

  it('escapes quotes and backslashes in strings', () => {
    expect(renderSampleProjects(rows(), "o'shop\\x")).toContain("\n    name: 'o\\'shop\\\\x',\n");
  });
});
