import type { SeedRows } from '@codemind/adapter-store-postgres';
import { projectKey, seedId } from './deterministic-ids.js';

/**
 * Renders `packages/web/src/data/sample-projects.ts`, the web's sample-project constant (DIS-92
 * design D3), from the same rows as the seed: the project id is the one `renderSeedDump` writes and
 * the counts are those of the rows. The text depends only on the rows, never on their order; LF line
 * endings and a final line feed.
 *
 * @param rows The exported rows of one project, in any order.
 * @param projectName Name the project gets in the seed (never the temporary indexing name).
 * @returns The file content.
 */
export function renderSampleProjects(rows: SeedRows, projectName: string): string {
  const lines = [
    '// Generated by `npm run seed:build`; do not edit by hand.',
    '',
    'export const SAMPLE_PROJECTS = [',
    '  {',
    `    id: ${tsString(seedId(projectKey(projectName)))},`,
    `    name: ${tsString(projectName)},`,
    `    language: ${tsString(rows.project.language)},`,
    `    framework: ${rows.project.framework === null ? 'null' : tsString(rows.project.framework)},`,
    `    fileCount: ${rows.files.length},`,
    `    symbolCount: ${rows.symbols.length},`,
    `    edgeCount: ${rows.edges.length},`,
    `    commitCount: ${rows.commits.length},`,
    '  },',
    '] as const;',
  ];
  return `${lines.join('\n')}\n`;
}

/** A single-quoted TypeScript string literal, with `\` and `'` escaped. */
function tsString(value: string): string {
  return `'${value.replace(/\\/g, '\\\\').replace(/'/g, "\\'")}'`;
}
